name: Build and Publish Documentation

on:
  push:
    branches:
      - main  # Or your default branch, if it's not 'main'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Adjust as necessary

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_book_theme

      - name: Build documentation
        run: |
          cd docs
          sphinx-build -b html . _build/html

      - name: Create .nojekyll file
        run: touch docs/_build/html/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
